### ISSUE TITLE
How to use these themes ?

### ISSUE THREAD

**Issue by stuaxo** [squarrel/kivy-themes#1]
Hi,
   Do I need to add something to my apps build() to use these themes ?

S

**Comment by squarrel** [comment]
Hi,
No, not at all. You can just replace the defaulttheme-0.png file in your Kivy's installation (in the ../kivy/data/images folder) with one from these themes.

Milos

**Comment by stuaxo** [comment]
Ah, I use a virtualenv that I share between various projects, so will have to find a different method.
